name: Update other SDKS for registry SDK
on:
  push:
    branches: 
      - main
    paths:
      - ".openapi/registry-instance.json"

jobs:
  dispatch:
    env:
      APP_SERVICES_CI_TOKEN: ${{ secrets.CI_USER_TOKEN }}
    strategy:
      matrix:
        repo:
          - "redhat-developer/app-services-sdk-js"
          - "redhat-developer/app-services-sdk-java"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: KAS Fleet Manager OpenAPI changed
        # v2
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588
        with:
          token: ${{ env.APP_SERVICES_CI_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: openapi-spec-change
          client-payload: '{ "id": "registryinstance/v1", "download_url":"https://raw.githubusercontent.com/redhat-developer/app-services-sdk-go/main/.openapi/registry-instance.json"}'
